services:
  nginx:
    container_name: "${NGINX_CONTAINER_NAME:-nginx-reverse-proxy}"
    image: nginx:latest
    env_file:
      - ./.env
      - ../minecraft/.env
    ports:
      - "${NGINX_HOST_PORT:-80}:80"
      - "${NGINX_HOST_PORT_HTTPS:-443}:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
    networks:
      - homelab
    restart: unless-stopped

networks:
  homelab:
    external: true
    name: homelab
