name: CI for Nginx & Linkding

on:
  push:
    paths:
      - 'nginx/**'
      - 'linkding/**'
      - '.github/workflows/nginx-compose-ci.yml'
  pull_request:
    paths:
      - 'nginx/**'
      - 'linkding/**'

jobs:
  nginx:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nginx
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate docker-compose
        run: docker compose config

      - name: Validate nginx config
        run: |
          docker run --rm \
            --add-host=linkding:127.0.0.1 \
            -v "$PWD/conf.d:/etc/nginx/conf.d:ro" \
            nginx:stable-alpine nginx -t
  linkding:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: linkding
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Validate docker-compose
        run: docker compose config
